const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const slug = require('slugs');

const storeSchema = new mongoose.Schema({
    name: {
        type: String,
        trim: true, //trims uploaded strings before adding to the db
        required: 'Please enter a store name!' // could also just put true, however it is better to put an error msg like this
    },
    slug: String,
    description: {
        type: String,
        trim: true,
    },
    tags: [String],
    created: {
        type: Date,
        default: Date.now,
    },
    location: {
        type: {
            type: String,
            default: 'Point',
        },
        coordinates: [{
            type: Number,
            required: 'You must supply coordinates!',
        }],
        address: {
            type: String,
            required: 'You must supply an address!'
        },
    },
    photo: String,
    author: {
        type: mongoose.Schema.ObjectId,
        ref: 'User',
        required: 'You must supply an author'
    },
});

// Define our indexes, to make querying more efficient
storeSchema.index({
    name: 'text',
    description: 'text',
});

storeSchema.index({
    location: '2dsphere',
})


storeSchema.pre('save', async function(next) {
    if (!this.isModified('name')) {
        next();  //skip it
        return;
    }
    this.slug = slug(this.name);
    // before we save a new store with this name, check to see if any other stores with that name already exist in database
    // this is important bc the slug is generated by the name, and the slug is used in the URLs for the indivudal store pages.  So, if the
    // name is the same and the slug is the same, then all stores with the same name will point to the same URL.
    // So... find all the stores with the same name and add a number to the end of the slug to make it unique. 
    const slugRegEx = new RegExp(`^(${this.slug})((-[0-9]*$)?)$`, 'i');
    const storesWithSlug = await this.constructor.find({ slug: slugRegEx });
    
    if (storesWithSlug.length) {
        this.slug = `${this.slug}-${storesWithSlug.length + 1}`;
    }
    next();
})

// make our own methods that we can call on the Store model (aka Store object)
// this will find all the tags
// import to use a proper "function()" here b/c we need to refer to "this"
storeSchema.statics.getTagsList = function() {
    // tip: to visualize what's happening in the db w/ this aggregate, use res.json() in the storeController function that calls getTagsList to
    // print out what is being returned.
    return this.aggregate([
        { $unwind: '$tags' }, // makes a list of stores by tag 
        { $group: { _id: '$tags', count: { $sum: 1 } }},  // groups the stores by tag, and sums them up.  Creates new object like {"_id": "Tag Name", "count": 2}
        { $sort: { count: -1 }} // sort in descending order
    ]);
}

module.exports = mongoose.model('Store', storeSchema);